### ISSUE TITLE
Accumulate doesn't work correctly if debounced function returns nothing (undefined)

### ISSUE THREAD

**Issue by PieterScheffers** [bjoerge/debounce-promise#25]
The error It get is this:
```
(node:18886) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at /c/repositories/proforto/Profortool/grand-bazaar/packages/tricorp-materializer/node_modules/debounce-promise/dist/index.js:43:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

Example code:
```
const debounce = require('debounce-promise')

async function doIt(name) {
    console.log('name', name) // [ [ 'first' ], [ 'second' ], [ 'third' ] ]
    // return name // When returning a value, no error is thrown
}

const doItPlus = debounce(doIt, 100, { accumulate: true })

async function main() {
    const promises = [
        doItPlus('first'),
        doItPlus('second'),
        doItPlus('third'),
    ]

    await Promise.all(promises)
}

main()
```

Node version: `v13.3.0`

**Comment by PieterScheffers** [comment]
Catching errors of promises seperately.

```
const debounce = require('debounce-promise')

async function doIt(name) {
    console.log('name', name) // [ [ 'first' ], [ 'second' ], [ 'third' ] ]
    // return name // When returning a value, no error is thrown
}

const doItPlus = debounce(doIt, 100, { accumulate: true })

async function main() {
    const promises = [
        doItPlus('first').catch((error) => console.log('error1', error)),
        doItPlus('second').catch((error) => console.log('error2', error)),
        doItPlus('third').catch((error) => console.log('error3', error)),
    ]

    await Promise.all(promises)
}

main()
```

```
error1 TypeError: Cannot read property '0' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
error2 TypeError: Cannot read property '1' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
error3 TypeError: Cannot read property '2' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 2)

```

**Comment by soumen-roy-001** [comment]
It might be helpful for someone - https://codesandbox.io/p/sandbox/reacttextareaautocomplete-forked-543p8y, tried by creating a modified js file from the `debounce-promise` source code - already documented in the example's comment.
